### ISSUE TITLE
Dependency and model registry problems

### ISSUE THREAD

**Issue by aalloolm** [CLARUS-HE-Project/ai-toolkit#1]
1. Airflow
Several Python libraries required to develop our models have not been installed:
Pandas, numpy, sksurv, sklearn, boto3 and mlflow. We need instructions to add them manually or redeploy them with Docker.

![image](https://github.com/CLARUS-HE-Project/ai-toolkit/assets/146815561/df9d88fd-8131-495c-949d-e3ec8e203ab1)

2. Model registry
I cant find how to set up mlflow with MinIO’s database, specifically how to set up the credentials with mlflow’s Python library.
line 126, in track_run 
mlflow.sklearn.log_model(model, "model", registered_model_name=run_name) …
line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials

**Comment by aiturria-ikerlan** [comment]
Thank you for reporting these issues. Here are some suggestions that may help in resolving them:
1. Airflow
1.1. Add the dependencies to the `requirements.txt` for Airflow and Jupyter (if it will be used).
1.2. Delete the containers, images, and (volumes).
1.3. Recreate the images and containers.
2. Model registry
2.1. Please review the IP addresses and ports in case they have been altered. They should ideally be on the same machine and should not be required.
2.2. If necessary, you can load the environment variables adding the following variables to the configuration file `config.py`:
```python
AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]
AWS_SECRET_ACCESS_KEY = os.environ["AWS_SECRET_ACCESS_KEY"]
MLFLOW_S3_ENDPOINT_URL = os.environ["MLFLOW_S3_ENDPOINT_URL"]
```

**Comment by aalloolm** [comment]
Thanks to Ikerland's team, the second problem was solved by manually adding all environment variables in the code: 

os.environ['AWS_ACCESS_KEY_ID']= AWS_ACCESS_KEY_ID
os.environ['AWS_SECRET_ACCESS_KEY']= AWS_SECRET_ACCESS_KEY
os.environ['MLFLOW_S3_ENDPOINT_URL']= MLFLOW_S3_ENDPOINT_URL
os.environ['MLFLOW_ENDPOINT']= MLFLOW_ENDPOINT
os.environ['MLFLOW_EXPERIMENT']= MLFLOW_EXPERIMENT
